
# code: language=ansible
---
- hosts: localhost
  connection: local
  vars_files: ["var.yaml"]
  tasks:
    - name: Add apt repos
      block:
        - name: "Apt repo> add susa repo key"
          get_url:
            url: https://download.opensuse.org/repositories/home:manuelschneid3r/Debian_12/Release.key
            dest: "/etc/apt/trusted.gpg.d/suse.asc"
        - name: "Apt repo> add Suse repo"
          apt_repository:
            repo: "deb http://download.opensuse.org/repositories/home:/manuelschneid3r/Debian_12/ /"
            filename: suse

    - name: Install
      block:
        - name: "Install> install desktop environment"
          apt:
            name: ["gnome-core"]
        - name: "Install> GUI apps"
          apt:
            name: [ "terminator",  "firefox-esr" ]
        - name: "Install> CLI apps"
          apt:
            name: ["mc", "tmux", "vim", "aptitude", "tig", "curl"]
        - name: "Install> tools"
          apt:
            name: ["ansible", "docker-compose", "docker.io", "git", "stow", "zsh", "sudo", "snapd"]
        - name: Install> snap
          block:
            - name: Install> snap> classic
              snap:
                name: ["code"]
                classic: True
            - name: Install> snap> normal
              snap:
                name: ["discord"]


    - name: Add jan tu sudo group
      loop: "{{ SUDO_USERS }}"
      user:
        name: "{{ item }}"
        groups: sudo
        append: true

- hosts: localhost
  connection: local
  become: True
  vars_files: ["var.yaml"]
  become_user: "{{ USERS[0].USERNAME }}"
  tasks:
    - name: Oh My zsh
      block:
        - name: "Oh My zsh> check if zsh is default shell"
          stat:
            path: ~/.oh-my-zsh
          register: oh_my_zsh
        - name: "Oh My zsh> install"
          when: not (oh_my_zsh.stat.isdir is defined and oh_my_zsh.stat.isdir)
          shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        - name: "Oh My zsh> set zsh as default shell"
          become: True
          become_user: root
          user:
            name: "{{ USERS[0].USERNAME }}"
            shell: /bin/zsh

    - name: Dotfiles
      vars:
        repo: https://github.com/dvojak-cz/DotFiles.git
        path: "~/.dotfiles"
        ssh_repo: "git@github.com:dvojak-cz/DotFiles.git"
      block:
        - name: "Dotfiles> check if dotfiles directory exists"
          stat:
            path: "{{ path }}"
          register: dir
        - name: "Dotfiles> clone"
          when: not dir.stat.exists
          git:
            repo: "{{ repo }}"
            dest: "{{ path }}"
            clone: yes
            update: yes
        - name: "Dotfiles> set remote url to ssh"
          when: not dir.stat.exists
          command:
            cmd: git remote set-url origin {{ ssh_repo }}
            chdir: "{{ path }}"
        - name: Dotfiles> appy
          when: false and not dir.stat.exists
          command:
            cmd: make
            chdir: "{{ path }}"

    - name: SSH
      block:
        - name: create .ssh folder
          file:
            path: ~/.ssh/
            state: directory
        - name: Download ssh key
          get_url:
            url: https://owncloud.cesnet.cz/index.php/s/51hpuGkGaQZGa9q/download
            dest: ~/.ssh/id_rsa.zip
            mode: 0600

    - name: Users home
      loop: "{{ USERS[0].DIR }}"
      file:
        path: "{{ item }}"
        state: directory

    - name: VPN
      block:
        - name: VPN> fit vpn file
          get_url:
            url: https://help.fit.cvut.cz/vpn/media/fit-vpn.ovpn
            dest: "~/.vpn/fit-vpn.ovpn"

